/**
 * Prebuild script: runs before `astro build` via the `prebuild` npm script.
 *
 * 1. Generates terminal-data.ts from terminal-script.md
 * 2. Fetches Swift test/suite counts from the TUIkit README badge
 *    via GitHub API (consumed by astro.config.mjs as environment variables)
 *
 * Requires GITHUB_TOKEN env var for authenticated API access (optional but
 * recommended to avoid rate limiting).
 */

import { parseTerminalScript } from "../src/lib/terminal-parser";
import fs from "fs";
import path from "path";

// ── Terminal Data ─────────────────────────────────────────────────

const script = parseTerminalScript();
const terminalOutputPath = path.join(process.cwd(), "src", "components", "react", "terminal-data.ts");

const tsContent = `/**
 * Auto-generated from terminal-script.md
 * DO NOT EDIT THIS FILE DIRECTLY - Edit terminal-script.md instead
 */

import type { TerminalScript } from "../../lib/terminal-parser";

export const TERMINAL_SCRIPT: TerminalScript = ${JSON.stringify(script, null, 2)};
`;

fs.writeFileSync(terminalOutputPath, tsContent);
console.log("✓ Generated terminal-data.ts from terminal-script.md");
