/**
 * Prebuild script: runs before `astro build` via the `prebuild` npm script.
 *
 * 1. Generates terminal-data.ts from terminal-script.md
 * 2. Fetches Swift test/suite counts from the TUIkit README badge
 *    via GitHub API (consumed by astro.config.mjs as environment variables)
 *
 * Requires GITHUB_TOKEN env var for authenticated API access (optional but
 * recommended to avoid rate limiting).
 */

import { parseTerminalScript } from "../src/lib/terminal-parser";
import fs from "fs";
import path from "path";

// ── Terminal Data ─────────────────────────────────────────────────

const script = parseTerminalScript();
const terminalOutputPath = path.join(process.cwd(), "src", "components", "react", "terminal-data.ts");

const tsContent = `/**
 * Auto-generated from terminal-script.md
 * DO NOT EDIT THIS FILE DIRECTLY - Edit terminal-script.md instead
 */

import type { TerminalScript } from "../../lib/terminal-parser";

export const TERMINAL_SCRIPT: TerminalScript = ${JSON.stringify(script, null, 2)};
`;

fs.writeFileSync(terminalOutputPath, tsContent);
console.log("✓ Generated terminal-data.ts from terminal-script.md");

// ── Project Stats (via GitHub API) ────────────────────────────────

const REPO = "phranck/TUIkit";

/** Build common headers for GitHub API requests. */
function apiHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    Accept: "application/vnd.github+json",
    "User-Agent": "tuikit-website",
  };
  const token = process.env.GITHUB_TOKEN;
  if (token) {
    headers.Authorization = `Bearer ${token}`;
  }
  return headers;
}

/**
 * Fetch test and suite counts from the TUIkit README badge.
 * The README contains badges like "Tests-1037_passing" and text like
 * "1037 tests across 42 test suites". We parse both patterns.
 */
async function fetchTestCounts(): Promise<{ testCount: number; suiteCount: number }> {
  const headers = apiHeaders();

  try {
    const res = await fetch(`https://api.github.com/repos/${REPO}/readme`, { headers });
    if (!res.ok) {
      console.warn(`GitHub API ${res.status} fetching README`);
      return { testCount: 0, suiteCount: 0 };
    }

    const data = (await res.json()) as { content: string; encoding: string };
    const readme = Buffer.from(data.content, "base64").toString("utf-8");

    // Badge pattern: Tests-1037_passing or Tests-1100%2B_passing
    const badgeMatch = readme.match(/Tests-(\d+)(?:%2B|\+)?_passing/);
    const testCount = badgeMatch ? parseInt(badgeMatch[1], 10) : 0;

    // Text pattern: "1037 tests across 42 test suites" or "1100+ tests across 150+ test suites"
    const suiteMatch = readme.match(/(\d+)(?:\+)?\s+tests?\s+across\s+(\d+)(?:\+)?\s+test\s+suites?/);
    const suiteCount = suiteMatch ? parseInt(suiteMatch[2], 10) : 0;

    return { testCount, suiteCount };
  } catch (err) {
    console.warn("Failed to fetch test counts from GitHub:", err);
    return { testCount: 0, suiteCount: 0 };
  }
}

const { testCount, suiteCount } = await fetchTestCounts();

const statsPath = path.join(process.cwd(), "project-stats.json");
fs.writeFileSync(statsPath, JSON.stringify({ testCount, suiteCount }, null, 2));
console.log(`✓ Generated project-stats.json (${testCount} tests, ${suiteCount} suites)`);
